databases:
  - name: todolist-db
    databaseName: mysite
    user: mysite
    region: singapore
    plan: free

services:
  - type: web
    name: todo_list
    env: python
    plan: free
    branch: main
    buildCommand: "./build.sh"
    region: singapore
    startCommand: "gunicorn todo_list.wsgi:application --log-file -"